

###  api接口测试


@baseUrl = http://43.138.142.228:8001

############################################################# 币种

### 添加币种
POST {{baseUrl}}/coin/addcoin HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Disposition: form-data; name="image"; filename="1.png"

coin_name=ETH&full_name=eth

### 获取币种列表
GET {{baseUrl}}/coin/GetCoin HTTP/1.1

############################################################# 交易对

POST {{baseUrl}}/market/AddMarket HTTP/1.1
Content-Type: application/x-www-form-urlencoded

type=1&coin_id_base=1518615144756809728&coin_id_quote=1518615259705905152&places_price=2&places_amount=6&trade_min=10&trade_min_market_sell=0.0001&market_email=1@126.com&service_url=http://localhost:8000&market_password=123456&settlement_email=2@126.com&settlement_password=123456&sort=0&tag=主流币


POST {{baseUrl}}/Service/Manage HTTP/1.1
Content-Type: application/x-www-form-urlencoded

market=1508083887828504627
&status=1


###




###  api 接口
@baseUrl1 = http://localhost:5210

POST {{baseUrl1}}/Test/Init HTTP/1.1


###
POST {{baseUrl1}}/Test/PlaceOrderText HTTP/1.1






###
POST http://localhost:5227/api/order/OrderPlace HTTP/1.1
api_key:aaa
api_sign:aaaaa
api_timestamp:150814098000
Content-Type: application/x-www-form-urlencoded

symbol=btc/usdt&a=[{"client_id":"string","symbol":"string","side":1,"type":1,"trade_model":1,"price":0,"amount":0.1,"total":0.1,"trigger_hanging_price":0.1,"trigger_cancel_price":0.1}]



###
POST http://localhost:5227/Order/GetOrderById