### 管理服务
#    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJubyI6IjE1MDkzNTQ3NTU4NDYxODA4NjQiLCJ1c2VyX2lkIjoiMTUwODc1NTM2NzMzMTUwMDAzMiIsInVzZXJfbmFtZSI6InVzZXIwIiwiYXBwIjoiMSIsInB1YmxpY19rZXkiOiI8UlNBS2V5VmFsdWU-PE1vZHVsdXM-OVdDMGJ1cDQrdHBYWmh1UU90bXFyanVXWnNPaVY2dUw0OFIwSWtrcmVZNWJYanhUU2NXRWRTWUlVS2VCSHVFMmFkcGI2QW40RkczSkh2VEFyaC9wY0M1dmtyMERNU1pBdXdhNmpYMEpUV0kyVUlDREtrdEprVGs5QnNycHNScE50dWxaNGFOZytWODB5M1ErblZLc2dnOXBGdVNDOEIwK0Vsdkh2Sm9KNldVPTwvTW9kdWx1cz48RXhwb25lbnQ-QVFBQjwvRXhwb25lbnQ-PC9SU0FLZXlWYWx1ZT4iLCJleHAiOjE2NDg2OTM4MDIsImlzcyI6ImNvbS5hcGkiLCJhdWQiOiIyMjMzMyJ9.KJXohq69vBszEg2gK6TSHbE5MHnkSIhc8-j9hSsL13A

@baseUrl = http://localhost:5105

POST {{baseUrl}}/Service/Manage HTTP/1.1
Content-Type: application/x-www-form-urlencoded

market=1508083887828504627
&status=1


###




###  api 接口
@baseUrl1 = http://localhost:5210

POST {{baseUrl1}}/Test/Init HTTP/1.1


###
POST {{baseUrl1}}/Test/PlaceOrderText HTTP/1.1






###
POST http://localhost:5227/api/order/OrderPlace HTTP/1.1
api_key:aaa
api_sign:aaaaa
api_timestamp:150814098000
Content-Type: application/x-www-form-urlencoded

symbol=btc/usdt&a=[{"client_id":"string","symbol":"string","side":1,"type":1,"trade_model":1,"price":0,"amount":0.1,"total":0.1,"trigger_hanging_price":0.1,"trigger_cancel_price":0.1}]



###
POST http://localhost:5227/Order/GetOrderById